baseURL = "https://kennethworkman.com/"
languageCode = "en-us"
title = "Kenny Workman"
theme = "sam"

[params]
    dateform             = "Mon Jan 02, 2006"
    dateformfull         = "Mon Jan 2 2006 15:04:05 EST"
    favicon              = "dna.ico"
    homepage             = "main"
    footerText           = "copyright sucks"

# Metadata for Open Graph and Twitter
    title                = "Kenny Workman"

[[params.mainMenu]]
  link = "/research"
  text = "research"

[[params.mainMenu]]
  link = "https://notes.kenbw.com/docs"
  text = "notes"

[[params.mainMenu]]
  link = "/reading"
  text = "reading"

[[params.mainMenu]]
  link = "/writing"
  text = "writing"

[[params.mainMenu]]
  link = "/about"
  text = "about"

